export { default as Hero } from './slide-hero.svelte'
export { default as Overlay } from './slide-overlay.svelte'
export { default as Content } from './slide-content.svelte'
export { default as About } from './slide-about.svelte'
export { default as OnBoard } from './slide-onboard.svelte'